### PR TITLE
Add mypy to static check tooling

### PR DESCRIPTION
**Pull request by omikader**
Since Python does not have static or strong types, the only way to enforce that this library is following the interfaces defined in `aiomsa` is using `mypy`. This PR adds mypy to the list of static checks for this project. For now, it will fail, but once a new `aiomsa` release is cut and onosproject/onos-api#125 is merged and released, we should be all set.

### CODE REVIEW

**Comment by ray-milkey** [comment]
retest this please

**Comment by omikader** [comment]
Sounds good, will do! This depends on us cutting a new release of `aiomsa` and a new release of `onos-api`. No rush on either of these, though. Just wanted to get a draft PR up so I don't forget :)

Will follow up when this is ready.

**Comment by omikader** [comment]
@ray-milkey This one should be ready to go too :)

**Review by al8 — APPROVED** [review]
looks good to me

**Review by adibrastegarnia — APPROVED** [review]

**Comment by adibrastegarnia** [comment]
@omikader 
do you want to merge this?

**Comment by omikader** [comment]
@adibrastegarnia yes, that would be great. Thanks!

**Pull request merged**
